elasticsearch:
    image: elasticsearch:5.6
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - './volumes/esdata:/usr/share/elasticsearch/data:rw'    
    environment:
      - xpack.security.enabled=false
